/**
 * @file neutron/platform/linux_key.c
 * @brief Linux key input system
 * 
 * 
 * @copyright
 * This file is part of the Ethereal Operating System.
 * It is released under the terms of the BSD 3-clause license.
 * Please see the LICENSE file in the main repository for more details.
 * 
 * Copyright (C) 2025 Samuel Stuart
 */

#ifdef BUILDING_LINUX

#include <neutron/neutron.h>
#include <X11/Xlib.h>
#include <X11/keysym.h>

XIM im;
XIC ic;
extern Display *display;

typedef struct {
	KeySym keysym;
	nt_key_t key;
} nt_x11_keymap_entry_t;

#define NT_X11_KEYMAP_ENTRY(x11sym, ntkey) { (x11sym), (ntkey) }

static const nt_x11_keymap_entry_t nt_x11_keymap[] = {
	NT_X11_KEYMAP_ENTRY(XK_a, NT_KEY_A), NT_X11_KEYMAP_ENTRY(XK_A, NT_KEY_A),
	NT_X11_KEYMAP_ENTRY(XK_b, NT_KEY_B), NT_X11_KEYMAP_ENTRY(XK_B, NT_KEY_B),
	NT_X11_KEYMAP_ENTRY(XK_c, NT_KEY_C), NT_X11_KEYMAP_ENTRY(XK_C, NT_KEY_C),
	NT_X11_KEYMAP_ENTRY(XK_d, NT_KEY_D), NT_X11_KEYMAP_ENTRY(XK_D, NT_KEY_D),
	NT_X11_KEYMAP_ENTRY(XK_e, NT_KEY_E), NT_X11_KEYMAP_ENTRY(XK_E, NT_KEY_E),
	NT_X11_KEYMAP_ENTRY(XK_f, NT_KEY_F), NT_X11_KEYMAP_ENTRY(XK_F, NT_KEY_F),
	NT_X11_KEYMAP_ENTRY(XK_g, NT_KEY_G), NT_X11_KEYMAP_ENTRY(XK_G, NT_KEY_G),
	NT_X11_KEYMAP_ENTRY(XK_h, NT_KEY_H), NT_X11_KEYMAP_ENTRY(XK_H, NT_KEY_H),
	NT_X11_KEYMAP_ENTRY(XK_i, NT_KEY_I), NT_X11_KEYMAP_ENTRY(XK_I, NT_KEY_I),
	NT_X11_KEYMAP_ENTRY(XK_j, NT_KEY_J), NT_X11_KEYMAP_ENTRY(XK_J, NT_KEY_J),
	NT_X11_KEYMAP_ENTRY(XK_k, NT_KEY_K), NT_X11_KEYMAP_ENTRY(XK_K, NT_KEY_K),
	NT_X11_KEYMAP_ENTRY(XK_l, NT_KEY_L), NT_X11_KEYMAP_ENTRY(XK_L, NT_KEY_L),
	NT_X11_KEYMAP_ENTRY(XK_m, NT_KEY_M), NT_X11_KEYMAP_ENTRY(XK_M, NT_KEY_M),
	NT_X11_KEYMAP_ENTRY(XK_n, NT_KEY_N), NT_X11_KEYMAP_ENTRY(XK_N, NT_KEY_N),
	NT_X11_KEYMAP_ENTRY(XK_o, NT_KEY_O), NT_X11_KEYMAP_ENTRY(XK_O, NT_KEY_O),
	NT_X11_KEYMAP_ENTRY(XK_p, NT_KEY_P), NT_X11_KEYMAP_ENTRY(XK_P, NT_KEY_P),
	NT_X11_KEYMAP_ENTRY(XK_q, NT_KEY_Q), NT_X11_KEYMAP_ENTRY(XK_Q, NT_KEY_Q),
	NT_X11_KEYMAP_ENTRY(XK_r, NT_KEY_R), NT_X11_KEYMAP_ENTRY(XK_R, NT_KEY_R),
	NT_X11_KEYMAP_ENTRY(XK_s, NT_KEY_S), NT_X11_KEYMAP_ENTRY(XK_S, NT_KEY_S),
	NT_X11_KEYMAP_ENTRY(XK_t, NT_KEY_T), NT_X11_KEYMAP_ENTRY(XK_T, NT_KEY_T),
	NT_X11_KEYMAP_ENTRY(XK_u, NT_KEY_U), NT_X11_KEYMAP_ENTRY(XK_U, NT_KEY_U),
	NT_X11_KEYMAP_ENTRY(XK_v, NT_KEY_V), NT_X11_KEYMAP_ENTRY(XK_V, NT_KEY_V),
	NT_X11_KEYMAP_ENTRY(XK_w, NT_KEY_W), NT_X11_KEYMAP_ENTRY(XK_W, NT_KEY_W),
	NT_X11_KEYMAP_ENTRY(XK_x, NT_KEY_X), NT_X11_KEYMAP_ENTRY(XK_X, NT_KEY_X),
	NT_X11_KEYMAP_ENTRY(XK_y, NT_KEY_Y), NT_X11_KEYMAP_ENTRY(XK_Y, NT_KEY_Y),
	NT_X11_KEYMAP_ENTRY(XK_z, NT_KEY_Z), NT_X11_KEYMAP_ENTRY(XK_Z, NT_KEY_Z),

	NT_X11_KEYMAP_ENTRY(XK_0, NT_KEY_0), NT_X11_KEYMAP_ENTRY(XK_KP_0, NT_KEY_KEYPAD0),
	NT_X11_KEYMAP_ENTRY(XK_1, NT_KEY_1), NT_X11_KEYMAP_ENTRY(XK_KP_1, NT_KEY_KEYPAD1),
	NT_X11_KEYMAP_ENTRY(XK_2, NT_KEY_2), NT_X11_KEYMAP_ENTRY(XK_KP_2, NT_KEY_KEYPAD2),
	NT_X11_KEYMAP_ENTRY(XK_3, NT_KEY_3), NT_X11_KEYMAP_ENTRY(XK_KP_3, NT_KEY_KEYPAD3),
	NT_X11_KEYMAP_ENTRY(XK_4, NT_KEY_4), NT_X11_KEYMAP_ENTRY(XK_KP_4, NT_KEY_KEYPAD4),
	NT_X11_KEYMAP_ENTRY(XK_5, NT_KEY_5), NT_X11_KEYMAP_ENTRY(XK_KP_5, NT_KEY_KEYPAD5),
	NT_X11_KEYMAP_ENTRY(XK_6, NT_KEY_6), NT_X11_KEYMAP_ENTRY(XK_KP_6, NT_KEY_KEYPAD6),
	NT_X11_KEYMAP_ENTRY(XK_7, NT_KEY_7), NT_X11_KEYMAP_ENTRY(XK_KP_7, NT_KEY_KEYPAD7),
	NT_X11_KEYMAP_ENTRY(XK_8, NT_KEY_8), NT_X11_KEYMAP_ENTRY(XK_KP_8, NT_KEY_KEYPAD8),
	NT_X11_KEYMAP_ENTRY(XK_9, NT_KEY_9), NT_X11_KEYMAP_ENTRY(XK_KP_9, NT_KEY_KEYPAD9),

	NT_X11_KEYMAP_ENTRY(XK_space, NT_KEY_SPACE),
	NT_X11_KEYMAP_ENTRY(XK_Return, NT_KEY_ENTER), NT_X11_KEYMAP_ENTRY(XK_KP_Enter, NT_KEY_KEYPADENTER),
	NT_X11_KEYMAP_ENTRY(XK_Escape, NT_KEY_ESCAPE),
	NT_X11_KEYMAP_ENTRY(XK_Tab, NT_KEY_TAB), NT_X11_KEYMAP_ENTRY(XK_ISO_Left_Tab, NT_KEY_TAB),
	NT_X11_KEYMAP_ENTRY(XK_BackSpace, NT_KEY_BACKSPACE),
	NT_X11_KEYMAP_ENTRY(XK_minus, NT_KEY_MINUS), NT_X11_KEYMAP_ENTRY(XK_KP_Subtract, NT_KEY_KEYPADSUBTRACT),
	NT_X11_KEYMAP_ENTRY(XK_equal, NT_KEY_EQUALS), NT_X11_KEYMAP_ENTRY(XK_KP_Equal, NT_KEY_KEYPADEQUALS),
	NT_X11_KEYMAP_ENTRY(XK_bracketleft, NT_KEY_LEFTBRACKET),
	NT_X11_KEYMAP_ENTRY(XK_bracketright, NT_KEY_RIGHTBRACKET),
	NT_X11_KEYMAP_ENTRY(XK_backslash, NT_KEY_BACKSLASH),
	NT_X11_KEYMAP_ENTRY(XK_semicolon, NT_KEY_SEMICOLON),
	NT_X11_KEYMAP_ENTRY(XK_apostrophe, NT_KEY_APOSTROPHE),
	NT_X11_KEYMAP_ENTRY(XK_grave, NT_KEY_GRAVE),
	NT_X11_KEYMAP_ENTRY(XK_comma, NT_KEY_COMMA),
	NT_X11_KEYMAP_ENTRY(XK_period, NT_KEY_PERIOD), NT_X11_KEYMAP_ENTRY(XK_KP_Decimal, NT_KEY_KEYPADDECIMAL),
	NT_X11_KEYMAP_ENTRY(XK_slash, NT_KEY_SLASH), NT_X11_KEYMAP_ENTRY(XK_KP_Divide, NT_KEY_KEYPADDIVIDE),
	NT_X11_KEYMAP_ENTRY(XK_KP_Multiply, NT_KEY_KEYPADMULTIPLY), NT_X11_KEYMAP_ENTRY(XK_KP_Add, NT_KEY_KEYPADADD),

	NT_X11_KEYMAP_ENTRY(XK_Insert, NT_KEY_INSERT), NT_X11_KEYMAP_ENTRY(XK_Delete, NT_KEY_DELETE),
	NT_X11_KEYMAP_ENTRY(XK_Home, NT_KEY_HOME), NT_X11_KEYMAP_ENTRY(XK_End, NT_KEY_END),
	NT_X11_KEYMAP_ENTRY(XK_Page_Up, NT_KEY_PAGEUP), NT_X11_KEYMAP_ENTRY(XK_Page_Down, NT_KEY_PAGEDOWN),
	NT_X11_KEYMAP_ENTRY(XK_Left, NT_KEY_LEFT), NT_X11_KEYMAP_ENTRY(XK_Right, NT_KEY_RIGHT),
	NT_X11_KEYMAP_ENTRY(XK_Up, NT_KEY_UP), NT_X11_KEYMAP_ENTRY(XK_Down, NT_KEY_DOWN),

	NT_X11_KEYMAP_ENTRY(XK_Caps_Lock, NT_KEY_CAPSLOCK),
	NT_X11_KEYMAP_ENTRY(XK_Scroll_Lock, NT_KEY_SCROLLLOCK),
	NT_X11_KEYMAP_ENTRY(XK_Num_Lock, NT_KEY_NUMLOCK),
	NT_X11_KEYMAP_ENTRY(XK_Print, NT_KEY_PRINTSCREEN),
	NT_X11_KEYMAP_ENTRY(XK_Pause, NT_KEY_PAUSE),

	NT_X11_KEYMAP_ENTRY(XK_F1, NT_KEY_F1), NT_X11_KEYMAP_ENTRY(XK_F2, NT_KEY_F2),
	NT_X11_KEYMAP_ENTRY(XK_F3, NT_KEY_F3), NT_X11_KEYMAP_ENTRY(XK_F4, NT_KEY_F4),
	NT_X11_KEYMAP_ENTRY(XK_F5, NT_KEY_F5), NT_X11_KEYMAP_ENTRY(XK_F6, NT_KEY_F6),
	NT_X11_KEYMAP_ENTRY(XK_F7, NT_KEY_F7), NT_X11_KEYMAP_ENTRY(XK_F8, NT_KEY_F8),
	NT_X11_KEYMAP_ENTRY(XK_F9, NT_KEY_F9), NT_X11_KEYMAP_ENTRY(XK_F10, NT_KEY_F10),
	NT_X11_KEYMAP_ENTRY(XK_F11, NT_KEY_F11), NT_X11_KEYMAP_ENTRY(XK_F12, NT_KEY_F12),
	NT_X11_KEYMAP_ENTRY(XK_F13, NT_KEY_F13), NT_X11_KEYMAP_ENTRY(XK_F14, NT_KEY_F14),
	NT_X11_KEYMAP_ENTRY(XK_F15, NT_KEY_F15), NT_X11_KEYMAP_ENTRY(XK_F16, NT_KEY_F16),
	NT_X11_KEYMAP_ENTRY(XK_F17, NT_KEY_F17), NT_X11_KEYMAP_ENTRY(XK_F18, NT_KEY_F18),
	NT_X11_KEYMAP_ENTRY(XK_F19, NT_KEY_F19), NT_X11_KEYMAP_ENTRY(XK_F20, NT_KEY_F20),
	NT_X11_KEYMAP_ENTRY(XK_F21, NT_KEY_F21), NT_X11_KEYMAP_ENTRY(XK_F22, NT_KEY_F22),
	NT_X11_KEYMAP_ENTRY(XK_F23, NT_KEY_F23), NT_X11_KEYMAP_ENTRY(XK_F24, NT_KEY_F24),

	NT_X11_KEYMAP_ENTRY(XK_Shift_L, NT_KEY_LEFTSHIFT), NT_X11_KEYMAP_ENTRY(XK_Shift_R, NT_KEY_RIGHTSHIFT),
	NT_X11_KEYMAP_ENTRY(XK_Control_L, NT_KEY_LEFTCTRL), NT_X11_KEYMAP_ENTRY(XK_Control_R, NT_KEY_RIGHTCTRL),
	NT_X11_KEYMAP_ENTRY(XK_Alt_L, NT_KEY_LEFTALT), NT_X11_KEYMAP_ENTRY(XK_Alt_R, NT_KEY_RIGHTALT),
	NT_X11_KEYMAP_ENTRY(XK_Super_L, NT_KEY_LEFTSUPER), NT_X11_KEYMAP_ENTRY(XK_Super_R, NT_KEY_RIGHTSUPER),
	NT_X11_KEYMAP_ENTRY(XK_Menu, NT_KEY_MENU),

	NT_X11_KEYMAP_ENTRY(XK_KP_Home, NT_KEY_KEYPAD7), NT_X11_KEYMAP_ENTRY(XK_KP_Up, NT_KEY_KEYPAD8),
	NT_X11_KEYMAP_ENTRY(XK_KP_Page_Up, NT_KEY_KEYPAD9), NT_X11_KEYMAP_ENTRY(XK_KP_Left, NT_KEY_KEYPAD4),
	NT_X11_KEYMAP_ENTRY(XK_KP_Begin, NT_KEY_KEYPAD5), NT_X11_KEYMAP_ENTRY(XK_KP_Right, NT_KEY_KEYPAD6),
	NT_X11_KEYMAP_ENTRY(XK_KP_End, NT_KEY_KEYPAD1), NT_X11_KEYMAP_ENTRY(XK_KP_Down, NT_KEY_KEYPAD2),
	NT_X11_KEYMAP_ENTRY(XK_KP_Page_Down, NT_KEY_KEYPAD3), NT_X11_KEYMAP_ENTRY(XK_KP_Insert, NT_KEY_KEYPAD0)
};

static nt_key_t nt_platform_key_from_keysym(KeySym keysym) {
	for (size_t i = 0; i < sizeof(nt_x11_keymap) / sizeof(nt_x11_keymap[0]); ++i) {
		if (nt_x11_keymap[i].keysym == keysym) {
			return nt_x11_keymap[i].key;
		}
	}

	return NT_KEY_UNKNOWN;
}

static uint32_t nt_platform_translate_modifiers(unsigned int state) {
	uint32_t modifiers = 0;

	if (state & ShiftMask) modifiers |= NT_MOD_SHIFT;
	if (state & ControlMask) modifiers |= NT_MOD_CTRL;
	if (state & Mod1Mask) modifiers |= NT_MOD_ALT;
	if (state & Mod4Mask) modifiers |= NT_MOD_SUPER;
	if (state & LockMask) modifiers |= NT_MOD_CAPS_LOCK;
	if (state & Mod2Mask) modifiers |= NT_MOD_NUM_LOCK;

	return modifiers;
}

bool nt_platform_xkeyevent_to_event(XKeyEvent *xkey, bool pressed, nt_event_t *event) {
	if (!xkey || !event) {
		return false;
	}

	KeySym keysym = XLookupKeysym(xkey, 0);
	nt_key_t key = nt_platform_key_from_keysym(keysym);

	event->type = pressed ? NT_EVENT_KEY_DOWN : NT_EVENT_KEY_UP;
	event->key.key = key;
	event->key.modifiers = nt_platform_translate_modifiers(xkey->state);

    int status;
    int len = Xutf8LookupString(ic, xkey, event->key.utf, 16, &keysym, &status);
    if (status == XBufferOverflow) assert(0 && "XBufferOverflow");
    if (len >= 0) event->key.utf[len] = 0;
    else event->key.utf[0] = 0;

	return true;
}

void nt_platform_x11_input_init(Window window) {
    im = XOpenIM(display, NULL, NULL, NULL);
    ic = XCreateIC(im, XNInputStyle, XIMPreeditNothing | XIMStatusNothing, XNClientWindow, window, NULL);

}

#endif