/**
 * @file include/neutron/event.h
 * @brief Neutron event system
 * 
 * 
 * @copyright
 * This file is part of the Ethereal Operating System.
 * It is released under the terms of the BSD 3-clause license.
 * Please see the LICENSE file in the main repository for more details.
 * 
 * Copyright (C) 2025 Samuel Stuart
 */

#ifndef _NEUTRON_EVENT_H
#define _NEUTRON_EVENT_H

#include <stdint.h>
#include <neutron/keycodes.h>

// Synthetic events are generated by the event system
typedef enum {
    NT_EVENT_MOUSE_ENTER,           // SYNTHETIC
    NT_EVENT_MOUSE_LEAVE,           // SYNTHETIC
    NT_EVENT_MOUSE_MOTION,        
    NT_EVENT_MOUSE_DOWN,
    NT_EVENT_MOUSE_UP,
    NT_EVENT_MOUSE_SCROLL,
    NT_EVENT_MOUSE_DOUBLE_CLICK,    // Lmao
    NT_EVENT_KEY_DOWN,
    NT_EVENT_KEY_UP,
    NT_EVENT_FOCUS_ENTER,           // SYNTHETIC
    NT_EVENT_FOCUS_EXIT,            // SYNTHETIC
    NT_EVENT_SELECTED,              // SYNTHETIC
    NT_EVENT_UNSELECTED,            // SYNTHETIC
    NT_EVENT_WINDOW_CLOSE,
    NT_EVENT_CHILD_WINDOW_CLOSE,
} nt_event_type_t;

#define NT_NEVENTS 15

#define NT_MOUSE_BUTTON_LEFT        0x1
#define NT_MOUSE_BUTTON_RIGHT       0x2
#define NT_MOUSE_BUTTON_MIDDLE      0x4

/**
 * The primary @c nt_event structure. Depending on the event type you will use the corresponding subtype.
 * 
 * For any mouse events, the pointer structure has all the possible fields.
 */
typedef struct _nt_event {
    struct _nt_widget *w; // the lowest widget the event got triggered on
    nt_event_type_t type;

    union {
        struct {
            unsigned int x;
            unsigned int y;
            unsigned char buttons;
        } pointer;

        struct {
            nt_key_t key;
            uint32_t modifiers;
            char utf[16];
        } key;

        struct {
            unsigned int x;
            unsigned int y;
            int delta_x;
            int delta_y;
        } scroll;

        struct {
            struct _nt_window *window;
        } window;
    };
} nt_event_t;

struct _nt_window;
struct _nt_widget;


// return TRUE to continue bubbling up the event, FALSE to stop it from bubbling up
typedef bool (*nt_event_handler_t)(struct _nt_widget *widget, nt_event_t *event);

void nt_event_process(struct _nt_window *window, nt_event_t *event);
void nt_event_set_handler(struct _nt_widget *widget, nt_event_type_t type, nt_event_handler_t event_handler);

static inline bool nt_event_is_pointer(nt_event_t *event) {
    return event->type == NT_EVENT_MOUSE_DOWN
        || event->type == NT_EVENT_MOUSE_MOTION
        || event->type == NT_EVENT_MOUSE_UP
        || event->type == NT_EVENT_MOUSE_ENTER
        || event->type == NT_EVENT_MOUSE_LEAVE
        || event->type == NT_EVENT_MOUSE_SCROLL
        || event->type == NT_EVENT_MOUSE_DOUBLE_CLICK;
}

static inline bool nt_event_is_keyboard(nt_event_t *event) {
    return event->type == NT_EVENT_KEY_DOWN
        || event->type == NT_EVENT_KEY_UP;
}

static inline bool nt_event_is_selected(nt_event_t *event) {
    return event->type == NT_EVENT_SELECTED
        || event->type == NT_EVENT_UNSELECTED;
}

static inline bool nt_event_is_window(nt_event_t *event) {
    return event->type == NT_EVENT_WINDOW_CLOSE
        || event->type == NT_EVENT_CHILD_WINDOW_CLOSE;
}

static inline bool nt_event_can_bubble(nt_event_t *event) {
    // only certain events can bubble. we wouldn't want a NT_EVENT_MOUSE_LEAVE event for a subwidget bubbling up to the parent
    return !(event->type == NT_EVENT_MOUSE_LEAVE || event->type == NT_EVENT_MOUSE_ENTER);
}

#endif
